language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
  - php: '7.4'
  - php: nightly

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.dist.xml --testdox

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
